# Generated by Django 5.2.7 on 2025-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwroty', '0007_alter_returnorder_tape_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_time_recive',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
