# Generated by Django 5.2.7 on 2025-10-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zwroty', '0008_product_date_time_recive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_time_recive',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
